# Generated by Django 2.1.5 on 2019-09-12 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=256, unique=True, verbose_name='Название продукта')),
                ('proteins', models.PositiveIntegerField(verbose_name='Белки')),
                ('fats', models.PositiveIntegerField(verbose_name='Жиры')),
                ('carbohydrates', models.PositiveIntegerField(verbose_name='Углеводы')),
                ('calories', models.PositiveIntegerField(verbose_name='КилоКалории')),
                ('weight', models.PositiveIntegerField(default='100', verbose_name='Вес продукта гр.')),
            ],
        ),
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_food', models.PositiveIntegerField(default='100', verbose_name='К-во продукта')),
                ('data_time_add_product', models.DateTimeField(default=django.utils.timezone.now)),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
