# Generated by Django 2.1.5 on 2019-09-19 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=256, unique=True, verbose_name='Название продукта')),
                ('proteins', models.FloatField(verbose_name='Белки')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('calories', models.FloatField(verbose_name='КилоКалории')),
                ('weight', models.FloatField(default='100.0', verbose_name='Вес продукта гр.')),
                ('categories', models.IntegerField(choices=[(1, 'Предложен'), (2, 'Утвержден')], default=1, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_born', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('photo', models.FileField(default='static/photo/Dogg.jpeg', upload_to='static/photo')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_food', models.FloatField(default='100', verbose_name='К-во продукта')),
                ('data_time_add_product', models.DateField(default=django.utils.timezone.now)),
                ('count_calories', models.FloatField(verbose_name='Ккал расчет')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Food', verbose_name='Название продукта')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
