# Generated by Django 2.1.5 on 2019-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='dima',
            field=models.CharField(default='1', max_length=192),
        ),
    ]
