# Generated by Django 2.1.5 on 2019-09-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_profileuser_dima'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='dima1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='photo',
            field=models.FileField(null=True, upload_to='static/photo'),
        ),
    ]
