# Generated by Django 2.1.5 on 2019-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20190917_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='dima1',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='photo',
            field=models.FileField(default='DEFAULT VALUE', upload_to='static/photo'),
        ),
    ]
