# Generated by Django 2.1.5 on 2019-09-18 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20190917_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='date_born',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
    ]
