# Generated by Django 2.1.5 on 2019-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20190918_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='date_born',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='photo',
        ),
    ]
