# Generated by Django 2.1.5 on 2019-09-18 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20190918_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='date_born',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='photo',
            field=models.FileField(default='DEFAULT VALUE', upload_to='static/photo'),
        ),
    ]
